#!/usr/bin/bash

cat<<EOF

This script is no longer needed as dbt-workarea-env now automatically attaches
the directories of your work area repos to the DUNEDAQ_DB_PATH variable. Please
call schemaeditor directly instead

EOF

exit 0
